l=[]
l.append("Apple")
l.insert(1,"Banana")
l.insert(2,"Cherry")
l.insert(3,"Banana")
l.insert(4,"Melon")
print(l)
l2=l.copy()
print(l2)
l3=["Grapes", "Kiwi"]
l.extend(l3)
print(l)
print("The count of Banana here is : ",l.count("Banana"))
print("The index of first occurrence of Banana here is : ",l.index("Banana"))
l.remove("Kiwi")
l.pop(3)
print("After removing elements: ",l)
l.reverse()
print("The reverse of the list is : ",l)
l.sort(reverse=True)
print("The descending sorted list is :",l)
l.sort()
print("The ascending sorted list is : ",l)
