t=(2,4,5,3,2,1)
print(t[-1])
print(t[-4:-1])
print(t[:len(t)])
print(t[3])
print(t)
print(t.count(2),"count of 2")
print(t.index(5),"index of 5 in the list")
sorted(t)
print(t)
print("min of t",min(t))
print("max of t",max(t))
